/**
 * DEFAULT_CONTENT — the single source of truth for every editable string / link
 * on the public site. The /admin panel stores an override JSON in Supabase which
 * is deep-merged over this object (see `getContent.ts`). Components read the
 * merged result, so if the DB is empty or unreachable the site renders these
 * values unchanged.
 *
 * Keep the shape flat-ish and JSON-serialisable (strings, numbers, arrays of the
 * two) — the admin form is generated by walking this tree.
 *
 * ⚠️ PLACEHOLDER CONTENT. This project ships only the design-agnostic content
 * groups (contacts, meta, header, footer, forms, modals, legal). Landing-page
 * section groups (hero / services / prices / etc.) are added once the «Премьер»
 * Figma handoff defines the sections — see PROJECT_STATE.md.
 */
import { PRICE_SALONS } from './prices'

export const DEFAULT_CONTENT = {
  /* ---- Контакты и ссылки ---- */
  contacts: {
    phoneDisplay: '+7 (495) 150-91-11',
    phoneHref: 'tel:+74951509111',
    email: 'Info1@premiersalon.ru',
    vk: 'https://vk.com/',
    telegram: 'https://t.me/premiermoscow',
    whatsapp: 'https://wa.me/74951509111',
    site: 'https://premiersalon.ru',
    maps: 'https://yandex.ru/maps/org/premyer/97206788511/',
    address: 'ул. Фадеева, 4А, Москва',
    hours: 'Ежедневно 10:00–22:00',
    hoursNote: 'Салоны на Новослободской и Таганской'
  },

  /* ---- Секция: Обложка (hero) ---- */
  hero: {
    eyebrow: 'Салон красоты в Москве',
    title: 'Красота с душой',
    noteLead: 'Создаём образы, в которых видно главное — ',
    noteAccent: 'Вас',
    cardBadge: 'Скидка',
    cardTitle: 'Скидка 20%',
    cardSub: 'на первый визит',
    cardBtn: 'Записаться'
  },

  /* ---- Секция: Акции ---- */
  promos: {
    title: 'Иногда приятно получить чуть больше, чем ожидал',
    subtitle: 'Приятные поводы заглянуть в «Премьер»',
    btnLabel: 'Записаться',
    allLabel: 'Посмотреть все предложения',
    allHref: '#promos',
    items: [
      {
        title: 'Название акции',
        desc: 'Описание',
        photo: '/images/promo-1.png'
      },
      {
        title: 'Название акции',
        desc: 'Описание',
        photo: '/images/promo-2.png'
      }
    ]
  },

  /* ---- Секция: Выбор салона ---- */
  salons: {
    title: 'Салоны с разным настроением',
    subtitle:
      'У каждого салона «Премьер» — свой ритм, настроение и характер. Выберите то, что ближе вам',
    btnLabel: 'Подробнее о локации',
    items: [
      {
        metro: 'Таганская',
        title: 'Камерная локация\nс атмосферой тишины',
        desc: 'Парикмахерский зал, ногтевой сервис, брови и ресницы, косметология, уход за телом',
        photo: '/images/salon-taganskaya.png',
        href: '#locations'
      },
      {
        metro: 'Новослободская',
        title: 'Просторный зал и современное оснащение',
        desc: 'Парикмахерский зал, ногтевой сервис, брови и ресницы, макияж',
        photo: '/images/salon-novoslobodskaya.png',
        href: '#locations'
      }
    ]
  },

  /* ---- Секция: Прайс-лист (выбор салона → залы/категории → таблицы услуг).
     Данные вынесены в src/shared/content/prices.ts (перенос из Figma). */
  prices: {
    title: 'Цены',
    chooseLabel: 'Выберите зал',
    chooseHint: 'Чтобы найти нужную услугу быстрее',
    salons: PRICE_SALONS
  },

  /* ---- Секция: О нас ---- */
  about: {
    title: 'Красота, которая говорит тихо',
    subtitle: 'Салоны «Премьер» — это про ту красоту, что не кричит',
    lead: 'Про уверенность, которая не требует подтверждений.',
    paragraphs: [
      'Мы вдохновляемся русской эстетикой — в её сдержанности, чистоте и силе. Добавляем к этому точность, современный подход и мастеров, которые видят суть.',
      'Мы за индивидуальность, спокойствие и аккуратность. За образы, в которых видно главное — человека.'
    ],
    outroLead: 'Красота — это вы.',
    outroAccent: '«Премьер» — это про красоту с корнями. И с будущим.',
    gallery: [
      '/images/about-photo.png',
      '/images/salon-taganskaya.png',
      '/images/salon-novoslobodskaya.png'
    ]
  },

  /* ---- Секция: Портфолио ---- */
  portfolio: {
    title: 'Красота — это вы',
    ctaText:
      'Каждая работа в «Премьере» — про вас. Мы не стараемся изменить, мы подчёркиваем.',
    ctaBtn: 'Хочу так же'
  },

  /* ---- Секция: Сертификаты и абонементы ---- */
  gifts: {
    title: 'Когда хочется подарить ощущения',
    subtitle:
      'Простое и стильное решение — как всё в «Премьере». Подойдут и для первого визита, и для тех, кто с нами давно.',
    btnLabel: 'Подарить опыт'
  },

  /* ---- Секция: Программа лояльности ---- */
  loyalty: {
    title: 'Ценим и хотим видеть вас чаще',
    subtitle: 'Приятно быть постоянным',
    items: [
      '20% на первый визит',
      'Кешбэк с каждой услуги',
      'Подарки на день рождения'
    ]
  },

  /* ---- Секция: Отзывы (реальные виджеты Яндекс.Карт) ---- */
  reviews: {
    title: 'Нас выбирают не случайно',
    intro:
      'Мы не подбираем цитаты. Просто берём настоящие отзывы тех, кто у нас был. Интеграция с Яндекс.Картами',
    quote: '«Уютно, спокойно, и всё — как хотела. Даже лучше»',
    widgets: [
      {
        label: 'Новослободская · ул. Фадеева, 4А',
        src: 'https://yandex.ru/maps-reviews-widget/97206788511?comments',
        link: 'https://yandex.ru/maps/org/premyer/97206788511/'
      },
      {
        label: 'Таганская · ул. Таганская, д.15 стр.2',
        src: 'https://yandex.ru/maps-reviews-widget/47027037547?comments',
        link: 'https://yandex.ru/maps/org/premyer/47027037547/'
      }
    ]
  },

  /* ---- Секция: Карта салонов (реальные виджеты Яндекс.Карт) ---- */
  locations: {
    title: 'Нас легко найти',
    subtitle: 'Удобные локации в центре города',
    btnLabel: 'Записаться',
    items: [
      {
        metro: 'Новослободская',
        address: 'ул. Фадеева, 4А, Москва',
        phone: '+7 (495) 150-91-11',
        hours: 'Ежедневно 10:00–22:00',
        mapSrc:
          'https://yandex.ru/map-widget/v1/?filter=alternate_vertical%3ARequestWindow&ll=37.601976%2C55.774734&mode=search&oid=97206788511&ol=biz&z=17'
      },
      {
        metro: 'Таганская',
        address: 'ул. Таганская, д.15 стр.2',
        phone: '+7 (495) 911-00-19',
        hours: 'Ежедневно 10:00–22:00',
        mapSrc:
          'https://yandex.ru/map-widget/v1/?ll=37.662098%2C55.740510&mode=search&oid=47027037547&ol=biz&z=17'
      }
    ]
  },

  /* ---- Метрика ---- */
  metrika: {
    // Yandex.Metrika counter id. Empty until configured (mirror of NEXT_PUBLIC_YM_ID).
    counterId: ''
  },

  /* ---- SEO / мета ---- */
  meta: {
    title: 'Премьер — салон красоты в Москве',
    titleTemplate: '%s — Премьер',
    applicationName: 'Премьер',
    description:
      'Салон красоты «Премьер» в Москве — два салона на Таганской и Новослободской. Стрижки и укладки, окрашивание и уход за волосами, маникюр и педикюр, брови и ресницы, косметология и уход за лицом. Запишитесь онлайн.',
    keywords: [
      'салон красоты',
      'салон красоты Москва',
      'салон красоты Таганская',
      'салон красоты Новослободская',
      'стрижки и укладки',
      'окрашивание волос',
      'маникюр и педикюр',
      'брови и ресницы',
      'косметология',
      'контурная пластика',
      'биоревитализация',
      'мезотерапия',
      'массаж',
      'депиляция'
    ]
  },

  /* ---- Шапка ---- */
  header: {
    nav: [
      { href: '#salons', label: 'Выбрать салон' },
      { href: '#prices', label: 'Цены' },
      { href: '#promos', label: 'Акции' },
      { href: '#gifts', label: 'Сертификаты' },
      { href: '#locations', label: 'Контакты' }
    ] as { href: string; label: string }[],
    ctaLabel: 'Записаться',
    routeText: 'Построить маршрут'
  },

  /* ---- Футер ---- */
  footer: {
    legalName: 'ООО «ПРЕМЬЕР», ИНН 7709837627, ОГРН 1097746558535',
    license: 'Мед. лицензия',
    licenseNumber: 'ЛО-77-01-021789 от 21.02.2022',
    legalReq: 'Реквизиты (ИНН, ОГРН и т. д.) — заполнить после ТЗ',
    vkPrefix: 'Мы в ',
    vkAccent: 'ВКонтакте',
    legalLinks: [
      { href: '/privacy', label: 'Политика конфиденциальности' }
    ]
  },

  /* ---- Формы (заявки) ---- */
  forms: {
    nameLabel: 'Имя*',
    namePlaceholder: 'Как вас зовут?',
    phoneLabel: 'Телефон*',
    consentPrefix: 'Я принимаю условия ',
    consentLink: 'Политики обработки персональных данных',
    consentSuffix: ' и даю согласие на обработку моих персональных данных.',
    error: 'Не удалось отправить заявку. Попробуйте ещё раз или позвоните нам.',
    sending: 'Отправляем…',
    submitBooking: 'Записаться'
  },

  /* ---- Модалки ---- */
  modals: {
    bookingTitle: 'Записаться в салон',
    thanksTitle: 'Ваша заявка принята!',
    thanksSubtitle:
      'Спасибо! Мы свяжемся с вами в ближайшее время для подтверждения записи.',
    thanksPrompt: 'Подписывайтесь на нас, чтобы следить за акциями и новостями:',
    subscribeLabel: 'Подписаться'
  },

  /* ---- Юридические страницы ---- */
  legal: {
    privacyTitle:
      'Политика обработки персональных данных и Пользовательское соглашение',
    privacyBlocks: [
      'Политика обработки персональных данных\nТекст политики будет добавлен после получения ТЗ и юридических данных салона «Премьер».'
    ],
    rulesTitle: 'Пользовательское соглашение',
    rulesBlocks: [
      '1. Общие положения\nТекст соглашения будет добавлен после получения ТЗ.'
    ]
  }
} as const

export type SiteContent = {
  -readonly [K in keyof typeof DEFAULT_CONTENT]: DeepMutable<
    (typeof DEFAULT_CONTENT)[K]
  >
}

type DeepMutable<T> = T extends readonly (infer U)[]
  ? DeepMutable<U>[]
  : T extends object
    ? { -readonly [K in keyof T]: DeepMutable<T[K]> }
    : T
